version: "3"
services:
  rogger:
    image: rogger
    restart: always
    hostname: rogger
    container_name: rogger
    ports:
      - 9000:9000
      - 8501:8501
    environment:
      HOST: 0.0.0.0
      PORT: 9000
      PROXY: http://192.168.20.204:2080
      FORCE_RENEW: False
      INSTANCE: v3
    networks:
      - nile
  
networks:
  nile:
    external: true

